entrega_3_mauro_silva/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('', include('inicio.urls')),
    path('admin/', admin.site.urls),
    
    
]

inicio/urls.py
from django.urls import path
from inicio import views

app_name = 'inicio'
urlpatterns = [
    path('', views.inicio, name = 'inicio') ,
    path('about/', views.about, name = 'about'),
        
    path("invitados/dejar_entrar", views.DejarEntrar.as_view(), name='dejar_entrar_invitado'),
    path('invitados', views.ListarInvitados.as_view(), name='listar_invitados'),
    path('invitados/sacar/<int:pk>', views.SacarInvitado.as_view(), name='sacar_invitado'),
    path('invitados/modificar_invitado/<int:pk>', views.ModificarInvitado.as_view(), name='mod_invitado'),
    path('invitados/mostrar_invitado/<int:pk>', views.MostrarInvitado.as_view(), name='mostrar_invitado'),

    path("djs/contratar_dj", views.ContratarDj.as_view(), name='contratar_dj'),
    path('djs', views.listar_djs, name='listar_djs'),
    path("djs/despedir/<int:pk>", views.DespedirDj.as_view(), name='despedir_dj'),
    path("djs/modificar_dj/<int:pk>", views.ModificarDj.as_view(), name='mod_dj'),
    path('djs/mostrar_dj/<int:pk>', views.MostrarDj.as_view(), name='mostrar_dj'),
]

proyecto_1_mauro_silva/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('inicio.urls')),
    path('usuario/', include('usuario.urls')),
    path('admin/', admin.site.urls),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

inicio/models.py
from django.db import models
from ckeditor.fields import RichTextField

class Invitado(models.Model):
    nombre = models.CharField(max_length=20)
    edad = models.IntegerField()
    descripcion = RichTextField(blank=True, null=True)
    imagen_invitado = models.ImageField(blank=True, null=True, upload_to='img_invitados')
    
    def __str__(self):
        return f'Invitado: {self.nombre} - Edad: {self.edad}'
    
class Dj(models.Model):
    nombre = models.CharField(max_length=20)
    canciones = models.IntegerField()
    descripcion = RichTextField(blank=True, null=True)
    fecha_de_presentacion = models.DateField(blank=True,null=True)
    imagen_dj = models.ImageField(blank=True, null=True, upload_to='img_djs')

    
    def __str__(self):
        return f'Dj: {self.nombre} - Canciones: {self.canciones}'

inicio/views.py
from django.shortcuts import render
from inicio.models import Invitado, Dj
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from inicio.form import BuscarDj

def inicio(request):
    return render(request, 'inicio/inicio.html')

def about(request):
    return render(request, 'inicio/about.html')


class DejarEntrar(LoginRequiredMixin, CreateView):
    model = Invitado
    template_name = 'inicio/CBV/dejar_entrar_CBV.html'
    fields = ['nombre', 'edad', 'descripcion']
    success_url = reverse_lazy('inicio:listar_invitados')

class ListarInvitados(ListView, ):
    model = Invitado
    template_name = 'inicio/CBV/listar_invitados_CBV.html'  
    context_object_name = 'invitados'
    
class ModificarInvitado(LoginRequiredMixin, UpdateView):
    model = Invitado
    template_name = 'inicio/CBV/modificar_invitado_CBV.html'  
    fields = ['nombre', 'edad', 'descripcion']
    success_url = reverse_lazy('inicio:listar_invitados')
    
class SacarInvitado(LoginRequiredMixin, DeleteView):
    model = Invitado
    template_name = 'inicio/CBV/sacar_invitado_CBV.html'  
    success_url = reverse_lazy('inicio:listar_invitados') 
    
class MostrarInvitado(DetailView):
    model = Invitado
    template_name = 'inicio/CBV/mostrar_invitado_CBV.html'

    
class ContratarDj(LoginRequiredMixin, CreateView):
      model = Dj
      template_name = 'inicio/CBV/contratar_dj_CBV.html'
      fields = ['nombre', 'canciones', 'descripcion','fecha_de_presentacion', 'imagen_dj']
      success_url = reverse_lazy('inicio:listar_djs')

def listar_djs(request):
    
    formulario = BuscarDj(request.GET)
    if formulario.is_valid():
        nombre_a_buscar = formulario.cleaned_data.get('nombre', '')
        djs = Dj.objects.filter(nombre__icontains=nombre_a_buscar)
    
    formulario = BuscarDj()
    return render(request, 'inicio/listar_djs.html', {'formulario':formulario, 'djs':djs})
    
    
class ModificarDj(LoginRequiredMixin, UpdateView):
    model = Dj
    template_name = 'inicio/CBV/modificar_dj_CBV.html'  
    fields = ['nombre', 'canciones', 'descripcion','fecha_de_presentacion', 'imagen_dj']
    success_url = reverse_lazy('inicio:listar_djs')
    
class DespedirDj(LoginRequiredMixin, DeleteView): 
    model = Dj
    template_name = 'inicio/CBV/despedir_dj_CBV.html'  
    success_url = reverse_lazy('inicio:listar_djs') 
    
class MostrarDj(DetailView):
    model = Dj
    template_name = 'inicio/CBV/mostrar_dj_CBV.html'    
    

inicio/templates/inicio/CBV/contratar_dj_CBV.html
{% extends 'base.html' %}

{% block titulo %}
<h2>Contratar un Dj:<h2/>
{% endblock titulo %}

{% block mensaje_inicio %}
Contratar un Dj:
{% endblock mensaje_inicio %}

{% block contenido %}

<form action={%url 'inicio:contratar_dj' %} method='POST' enctype='multipart/form-data'>
    {% csrf_token %}
    <table>
    {{form}}
    {{form.media}}
    </table>

    <button>Contratar</button>
    
</form>


{% endblock contenido %}

inicio/templates/inicio/CBV/dejar-entrar-CBV.html
{% extends 'base.html' %}

{% block titulo %}
<h2>Ingresar Invitado<h2/>
{% endblock titulo %}

{% block mensaje_inicio %}
Dejar entrar Invitado:
{% endblock mensaje_inicio %}

{% block contenido %}

<form action={%url 'inicio:dejar entrar invitado' %} method='POST'>
    {% csrf_token %}
    <table>
    {{form}}
    </table>

    <button>Dejar entrar</button>
    
</form>


{% endblock contenido %}

inicio/templates/inicio/CBV/despedir_dj_CBV.html
{% extends 'base.html' %}

{% block titulo %}
<h2>Despedir Dj<h2/>
{% endblock titulo %}

{% block mensaje_inicio %}
Despedir dj:
{% endblock mensaje_inicio %}

{% block contenido %}

<form action={%url 'inicio:despedir_dj' dj.id %} method='POST'>
    {% csrf_token %}
    <p>¿Desea despedir a {{dj}}?</p>
    <button>Confirmar</button>
    
</form>


{% endblock contenido %}

inicio/templates/inicio/CBV/listar_djs_CBV.html
{% extends 'base.html' %}

{% block titulo %}
<h2>Listado<h2/>
{% endblock titulo %}

{% block mensaje_inicio %}

Listado de Djs contratados:
{% endblock mensaje_inicio %}

{% block contenido %}
<button><a class='navbar-brand' href= {% url 'inicio:contratar_dj' %}>Contratar</a></button>

{% if djs %}
{% for dj in djs %}

<li>
    {{dj}}
    <a href={% url 'inicio:mostrar_dj' dj.id %}>Mostrar</a>
    <a href={% url 'inicio:mod_dj' dj.id %}>Modificar</a>
    <a href={% url 'inicio:despedir_dj' dj.id %}>Sacar</a>
</li>

{% endfor %}

{% else %}
<p>No hay Djs contratados aún.</p>
{% endif %}
{% endblock contenido %}

inicio/templates/inicio/CBV/modificar-dj-CBV.html
{% extends 'base.html' %}

{% block titulo %}
<h2>Modificar Dj<h2/>
{% endblock titulo %}

{% block mensaje_inicio %}
Modificar Dj:
{% endblock mensaje_inicio %}

{% block contenido %}

<form action={% url 'inicio:mod dj' dj.id %} method='POST'>
    {% csrf_token %}
    <table>
    {{form}}
    </table>
    
    <button>Modificar</button>
    
</form>


{% endblock contenido %}

inicio/templates/inicio/CBV/modificar-invitado-CBV.html
{% extends 'base.html' %}

{% block titulo %}
<h2>Modificar Invitado<h2/>
{% endblock titulo %}

{% block mensaje_inicio %}
Modificar Invitado:
{% endblock mensaje_inicio %}

{% block contenido %}

<form action={% url 'inicio:mod invitado' invitado.id %} method='POST'>
    {% csrf_token %}
    <table>
    {{form}}
    </table>
    
    <button>Modificar</button>
    
</form>


{% endblock contenido %}

inicio/templates/inicio/CBV/modificar-pista-CBV.html
{% extends 'base.html' %}

{% block titulo %}
<h2>Modificar Pista<h2/>
{% endblock titulo %}

{% block mensaje_inicio %}
Modificar Pista:
{% endblock mensaje_inicio %}

{% block contenido %}

<form action={% url 'inicio:mod pista' pista.id %} method='POST'>
    {% csrf_token %}
    <table>
    {{form}}
    </table>
    
    <button>Modificar</button>
    
</form>


{% endblock contenido %}

inicio/templates/inicio/CBV/modificar_dj_CBV.html
{% extends 'base.html' %}

{% block titulo %}
<h2>Modificar Dj<h2/>
{% endblock titulo %}

{% block mensaje_inicio %}
Modificar Dj {{dj.nombre}}:
{% endblock mensaje_inicio %}

{% block contenido %}

<form action={% url 'inicio:mod_dj' dj.id %} method='POST' enctype='multipart/form-data'>
    {% csrf_token %}
    <table>
    {{form}}
    {{form.media}}

    </table>
    
    <button>Modificar</button>
    
</form>


{% endblock contenido %}

inicio/templates/inicio/CBV/modificar_invitado_CBV.html
{% extends 'base.html' %}

{% block titulo %}
<h2>Modificar Invitado<h2/>
{% endblock titulo %}

{% block mensaje_inicio %}
Modificar Invitado:
{% endblock mensaje_inicio %}

{% block contenido %}

<form action={% url 'inicio:mod_invitado' invitado.id %} method='POST'>
    {% csrf_token %}
    <table>
    {{form}}
    {{form.media}}

    </table>
    
    <button>Modificar</button>
    
</form>


{% endblock contenido %}

inicio/templates/inicio/CBV/mostrar-dj-CBV.html
{% extends 'base.html' %}

{% block titulo %}
<h2>Dj<h2/>
{% endblock titulo %}

{% block mensaje_inicio %}
{{dj.nombre}}:
{% endblock mensaje_inicio %}

{% block contenido %}
<li>Canciones que toca: {{dj.canciones}}</li>
<li>Descripción: {{dj.descripcion}}</li>
{% endblock contenido %}

inicio/templates/inicio/CBV/mostrar-invitado-CBV.html
{% extends 'base.html' %}

{% block titulo %}
<h2>Invitado<h2/>
{% endblock titulo %}

{% block mensaje_inicio %}
{{invitado.nombre}}:
{% endblock mensaje_inicio %}

{% block contenido %}
<li>Edad: {{invitado.edad}}</li>
<li>Descripción: {{invitado.descripcion}}</li>
{% endblock contenido %}

inicio/templates/inicio/CBV/mostrar_dj_CBV.html
{% extends 'base.html' %}

{% block titulo %}
<h2>Dj<h2/>
{% endblock titulo %}

{% block mensaje_inicio %}
{{dj.nombre}}:
{% endblock mensaje_inicio %}

{% block contenido %}
<li>Canciones que toca: {{dj.canciones}}</li>
{% if dj.descripcion %}
<li>Descripción: {{dj.descripcion | safe}}</li>


{% endif %}
<li>Fecha de Presentación: {{dj.fecha_de_presentacion}}</li>
{% if dj.imagen_dj %}
<li><img src={{dj.imagen_dj.url}} alt = '' height = '480px' > </img></li>


{% endif %}
{% endblock contenido %}

inicio/templates/inicio/CBV/mostrar_invitado_CBV.html
{% extends 'base.html' %}

{% block titulo %}
<h2>Invitado<h2/>
{% endblock titulo %}

{% block mensaje_inicio %}
{{invitado.nombre}}:
{% endblock mensaje_inicio %}

{% block contenido %}
<li>Edad: {{invitado.edad}}</li>
<li>Descripción: {{invitado.descripcion | safe}}</li>
{% endblock contenido %}

inicio/templates/inicio/CBV/sacar-invitado-CBV.html
{% extends 'base.html' %}

{% block titulo %}
<h2>Sacar Invitado<h2/>
{% endblock titulo %}

{% block mensaje_inicio %}
Sacar Invitado:
{% endblock mensaje_inicio %}

{% block contenido %}

<form action={%url 'inicio:sacar invitado' invitado.id %} method='POST'>
    {% csrf_token %}
    <p>¿Desea sacar a {{invitado}}?</p>
    <button>Confirmar</button>
    
</form>


{% endblock contenido %}