entrega_3_mauro_silva/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('', include('inicio.urls')),
    path('admin/', admin.site.urls),
    
    
]

inicio/urls.py
from django.urls import path
from inicio import views

app_name = 'inicio'
urlpatterns = [
    path('', views.inicio, name = 'inicio') ,
    path('about/', views.about, name = 'about'),
        
    path("invitados/dejar_entrar", views.DejarEntrar.as_view(), name='dejar_entrar_invitado'),
    path('invitados', views.ListarInvitados.as_view(), name='listar_invitados'),
    path('invitados/sacar/<int:pk>', views.SacarInvitado.as_view(), name='sacar_invitado'),
    path('invitados/modificar_invitado/<int:pk>', views.ModificarInvitado.as_view(), name='mod_invitado'),
    path('invitados/mostrar_invitado/<int:pk>', views.MostrarInvitado.as_view(), name='mostrar_invitado'),

    path("djs/contratar_dj", views.ContratarDj.as_view(), name='contratar_dj'),
    path('djs', views.listar_djs, name='listar_djs'),
    path("djs/despedir/<int:pk>", views.DespedirDj.as_view(), name='despedir_dj'),
    path("djs/modificar_dj/<int:pk>", views.ModificarDj.as_view(), name='mod_dj'),
    path('djs/mostrar_dj/<int:pk>', views.MostrarDj.as_view(), name='mostrar_dj'),
]

proyecto_1_mauro_silva/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('inicio.urls')),
    path('usuario/', include('usuario.urls')),
    path('admin/', admin.site.urls),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

usuario/urls.py
from django.urls import path
from usuario import views
from django.contrib.auth.views import LogoutView

app_name = 'usuario'

urlpatterns = [
    path('login/',views.login, name='login'),
    path('registro/', views.registro, name='registro'),
    path('logout/', LogoutView.as_view(template_name='usuario/logout.html'), name='logout'),
    path('perfil', views.perfil, name = 'perfil'),
    path('perfil/editar/', views.editar_perfil, name = 'editar_perfil'),
    path('perfil/editar/pass', views.CambiarPass.as_view(), name = 'cambiar_pass'),
    path('resenias', views.listar_resenias, name = 'resenias'),
    path('resenias/postear', views.Postear.as_view(), name = 'postear'),
    path('resenias/editar_resenia/<int:pk>/', views.EditarResenia.as_view(), name='editar_resenia'),
    path('resenias/eliminar_resenia/<int:pk>/', views.EliminarResenia.as_view(), name = 'eliminar_resenia'),
    path('resenias/mostrar/<int:pk>/', views.MostrarResenia.as_view(), name = 'mostrar_resenia'),

]

usuario/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField


class InfoUsuario(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='avatares', null=True, blank=True)
    cumpleanios = models.DateField(blank=True, null=True)
    
class Resenia(models.Model):
    titulo = models.CharField(max_length=20)
    subtitulo = models.CharField(max_length=20)
    contenido = RichTextField(null=True, blank=True)
    autor = models.CharField(max_length=20)
    fecha_de_creacion = models.DateField(null=True)
    
    def __str__(self):
        return f'Reseña: {self.titulo}'
    

usuario/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login as django_login
from usuario.form import FormularioRegistro, FormularioEditarPerfil, BuscarResenia
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from usuario.models import InfoUsuario, Resenia
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from django.views.generic.detail import DetailView

def login(request):
    
    if request.method == 'POST':
        formulario = AuthenticationForm(request, data=request.POST)
        if formulario.is_valid():
            usuario = formulario.cleaned_data['username']
            contrasenia = formulario.cleaned_data['password']
            user = authenticate(username=usuario, password=contrasenia)
            
            django_login(request,user)
            
            InfoUsuario.objects.get_or_create(user=user)
            
            return redirect('inicio:inicio')
        else:
            return render(request, 'usuario/login.html', {'formulario':formulario})
    
    formulario = AuthenticationForm()
    return render(request, 'usuario/login.html', {'formulario':formulario})

def registro(request):
    
    if request.method == 'POST':
        formulario = FormularioRegistro(request.POST)
        if formulario.is_valid():
            formulario.save()
            return redirect('usuario:login')
        else:
            return render(request, 'usuario/registro.html', {'formulario':formulario}) 
    
    formulario = FormularioRegistro()
    return render(request, 'usuario/registro.html', {'formulario':formulario}) 

@login_required
def editar_perfil(request):
    info_extra_usuario = request.user.infousuario
    if request.method =='POST':
        formulario = FormularioEditarPerfil(request.POST, request.FILES, instance=request.user)
        if formulario.is_valid():
            avatar = formulario.cleaned_data.get('avatar')
            cumpleanios = formulario.cleaned_data.get('cumpleanios')
            if avatar: 
                info_extra_usuario.avatar = avatar
                info_extra_usuario.save()
            elif cumpleanios:
                info_extra_usuario.cumpleanios = cumpleanios
                info_extra_usuario.save()
            formulario.save()
            return redirect('inicio:inicio')
        else:
            return render(request, 'usuario/editar_perfil.html', {'formulario':formulario})
        
    else:
        formulario = FormularioEditarPerfil(initial={'avatar': info_extra_usuario.avatar}, instance=request.user)
    
    return render(request, 'usuario/editar_perfil.html', {'formulario':formulario}) 

class CambiarPass(LoginRequiredMixin, PasswordChangeView):
    template_name = 'usuario/cambiar_pass.html'
    success_url = reverse_lazy('usuario:editar_perfil')
    

class Postear(LoginRequiredMixin, CreateView):
     model = Resenia
     template_name = 'usuario/postear.html'
     fields = ['titulo', 'subtitulo', 'contenido', 'autor', 'fecha_de_creacion']
     success_url = reverse_lazy('usuario:resenias')

def listar_resenias(request):
    
    formulario = BuscarResenia(request.GET)
    if formulario.is_valid():
        titulo_a_buscar = formulario.cleaned_data.get('titulo', '')
        resenias = Resenia.objects.filter(titulo__icontains=titulo_a_buscar)
    
    formulario = BuscarResenia()
    return render(request, 'usuario/resenias.html', {'formulario':formulario, 'resenias':resenias})
 
class EditarResenia(LoginRequiredMixin, UpdateView):
      model = Resenia
      template_name = 'usuario/editar_resenia.html'  
      fields = ['titulo', 'subtitulo', 'contenido', 'autor', 'fecha_de_creacion']
      success_url = reverse_lazy('usuario:resenias') 

        
class EliminarResenia(LoginRequiredMixin, DeleteView): 
    model = Resenia
    template_name = 'usuario/eliminar_resenia.html'  
    success_url = reverse_lazy('usuario:resenias') 
    
class MostrarResenia(DetailView):
    model = Resenia
    template_name = 'usuario/mostrar_resenia.html'    
    
def perfil(request):
    return render(request, 'usuario/perfil.html')

usuario/templates/usuario/cambiar_pass.html
{% extends 'base.html' %}

{% block title_head %}
<title>Editar Contraseña<title/>
{% endblock title_head %}

{% block mensaje_inicio %}
Cambiar Contraseña
{% endblock mensaje_inicio %}

{% block contenido %}

<form action={%url 'usuario:cambiar_pass' %} method='POST'>
    {% csrf_token %}
    <table>
    {{form}}
    </table>
    <button>Confirmar</button>
</form>


{% endblock contenido %}

usuario/templates/usuario/editar_perfil.html
{% extends 'base.html' %}

{% block title_head %}
<title>Editar Perfil<title/>
{% endblock title_head %}

{% block mensaje_inicio %}
Editar Perfil
{% endblock mensaje_inicio %}

{% block contenido %}

<form action={%url 'usuario:editar_perfil' %} method='POST' enctype='multipart/form-data'>
    {% csrf_token %}
    <table>
    {{formulario}}
    </table>
    <button>Confirmar</button>
    <button type='button'><a class='navbar-brand' href={% url 'usuario:cambiar_pass' %}>Cambiar Contraseña</a> </button>
 
</form> 


{% endblock contenido %}

usuario/templates/usuario/editar_resenia.html
{% extends 'base.html' %}

{% block titulo %}
<h2>Editar Reseña:<h2/>
{% endblock titulo %}

{% block mensaje_inicio %}
Editar Reseña {{resenia.titulo}}:
{% endblock mensaje_inicio %}

{% block contenido %}

<form action={% url 'usuario:editar_resenia' resenia.id %} method='POST'>
    {% csrf_token %}
    <table>
    {{form}}
    {{form.media}}
    </table>
    
    <button type='submit'>Confirmar</button>
    
</form>



{% endblock contenido %}

usuario/templates/usuario/eliminar_resenia.html
{% extends 'base.html' %}

{% block titulo %}
<h2>Eliminar Reseña<h2/>
{% endblock titulo %}

{% block mensaje_inicio %}
Eliminar
{% endblock mensaje_inicio %}

{% block contenido %}

<form action={%url 'usuario:eliminar_resenia' resenia.id %} method='POST'>
    {% csrf_token %}
    <p>¿Desea eliminar la reseña{{resenia.titulo}}?</p>
    <button>Confirmar</button>
    
</form>


{% endblock contenido %}

usuario/templates/usuario/login.html
{% extends 'base.html' %}

{% block title_head %}
<title>Login<title/>
{% endblock title_head %}

{% block mensaje_inicio %}
Login
{% endblock mensaje_inicio %}

{% block contenido %}

<form action={%url 'usuario:login' %} method='POST'>
    {% csrf_token %}
    <table>
    {{formulario}}
    </table>

    <button>Login</button>
    
</form>


{% endblock contenido %}

usuario/templates/usuario/logout.html
{% extends 'base.html' %}


{% block titulo %}
<h2>Logout<h2/>
{% endblock titulo %}


{% block mensaje_inicio %}
Te has deslogueado con éxito. 
{% endblock mensaje_inicio %}

{% block contenido %}
{% endblock contenido %}

usuario/templates/usuario/mostrar_resenia.html
{% extends 'base.html' %}

{% block titulo %}
<h2>Reseña<h2/>
{% endblock titulo %}

{% block mensaje_inicio %}
{{resenia.titulo}}:
{% endblock mensaje_inicio %}

{% block contenido %}
<li>{{resenia.subtitulo}}</li>
<li>Autor: {{resenia.autor}}</li>
<li>{{resenia.contenido | safe }}</li>
<li>Fecha de Posteo: {{resenia.fecha_de_creacion}}</li>
<button type='button'><a class='navbar-brand' href={% url 'usuario:resenias' %}>Volver al listado</a> </button>
{% endblock contenido %}

usuario/templates/usuario/perfil.html
{% extends 'base.html' %}

{% block titulo %}
<h2>Perfil<h2/>
{% endblock titulo %}

{% block mensaje_inicio %}
Usuario: {{user.first_name}}:
{% endblock mensaje_inicio %}

{% block contenido %}
<li>Nombre del usuario: {{user.first_name}}</li>
<li>email: {{user.email}}</li>
<li>Apellido: {{user.last_name}}</li>
{% if request.user.infousuario.cumpleanios %}
<li>{{request.user.infousuario.cumpleanios}}</li>
{% endif %}
{% if user.infousuario.avatar %}
<li><img src={{request.user.infousuario.avatar.url}} alt = '' height = '480px' > </img></li>
{% endif %}


<button><a href={% url 'usuario:editar_perfil' %}>Editar Perfil</a></button>
{% endblock contenido %}

usuario/templates/usuario/postear.html
{% extends 'base.html' %}

{% block titulo %}
<h2>Postear Reseña<h2/>
{% endblock titulo %}

{% block mensaje_inicio %}
Redactar y Postear una Reseña
{% endblock mensaje_inicio %}

{% block contenido %}

<form action={%url 'usuario:postear' %} method='POST'>
    {% csrf_token %}
    <table>
    {{form}}
    {{form.media}}
    </table>

    <button>Postear</button>
    
</form>


{% endblock contenido %}
 

usuario/templates/usuario/registro.html
{% extends 'base.html' %}

{% block title_head %}
<title>Registro<title/>
{% endblock title_head %}

{% block mensaje_inicio %}
Crear usuario
{% endblock mensaje_inicio %}

{% block contenido %}

<form action={%url 'usuario:registro' %} method='POST' enctype='multipart/form-data'>
    {% csrf_token %}
    <table>
    {{formulario}}
    </table>

    <button>Crear usuario</button>
    
</form>


{% endblock contenido %}

usuario/templates/usuario/resenias.html
{% extends 'base.html' %}

{% block titulo %}
<h2>Listado<h2/>
{% endblock titulo %}

{% block mensaje_inicio %}
Listado de Reseñas:
{% endblock mensaje_inicio %}

{% block contenido %}
<button><a class='navbar-brand' href= {% url 'usuario:postear' %}>Postear Nueva Reseña</a></button>

<form action={% url 'usuario:resenias' %} method='get'>
    <table>
        {{formulario}} 
    </table>
    <button>Buscar</button>
</form>
{% if resenias %}
{% for resenia in resenias %}
<li>
    {{resenia}}
    <a href={% url 'usuario:mostrar_resenia' resenia.id %}>Mostrar</a>
    <a href={% url 'usuario:editar_resenia' resenia.id %}>Editar</a>
    <a href={% url 'usuario:eliminar_resenia' resenia.id %}>Eliminar</a>
</li>
{% endfor %}
{% else %}
<p>No se encontro Reseña.</p>
{% endif %}
{% endblock contenido %}