entrega_3_mauro_silva/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('', include('inicio.urls')),
    path('admin/', admin.site.urls),
    
    
]

inicio/urls.py
from django.urls import path
from inicio import views

app_name = 'inicio'
urlpatterns = [
    path('', views.inicio, name = 'inicio') ,
    path('about/', views.about, name = 'about'),
        
    path("invitados/dejar_entrar", views.DejarEntrar.as_view(), name='dejar_entrar_invitado'),
    path('invitados', views.ListarInvitados.as_view(), name='listar_invitados'),
    path('invitados/sacar/<int:pk>', views.SacarInvitado.as_view(), name='sacar_invitado'),
    path('invitados/modificar_invitado/<int:pk>', views.ModificarInvitado.as_view(), name='mod_invitado'),
    path('invitados/mostrar_invitado/<int:pk>', views.MostrarInvitado.as_view(), name='mostrar_invitado'),

    path("djs/contratar_dj", views.ContratarDj.as_view(), name='contratar_dj'),
    path('djs', views.listar_djs, name='listar_djs'),
    path("djs/despedir/<int:pk>", views.DespedirDj.as_view(), name='despedir_dj'),
    path("djs/modificar_dj/<int:pk>", views.ModificarDj.as_view(), name='mod_dj'),
    path('djs/mostrar_dj/<int:pk>', views.MostrarDj.as_view(), name='mostrar_dj'),
]

proyecto_1_mauro_silva/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('inicio.urls')),
    path('usuario/', include('usuario.urls')),
    path('admin/', admin.site.urls),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

usuario/urls.py
from django.urls import path
from usuario import views
from django.contrib.auth.views import LogoutView

app_name = 'usuario'

urlpatterns = [
    path('login/',views.login, name='login'),
    path('registro/', views.registro, name='registro'),
    path('logout/', LogoutView.as_view(template_name='usuario/logout.html'), name='logout'),
    path('perfil', views.perfil, name = 'perfil'),
    path('perfil/editar/', views.editar_perfil, name = 'editar_perfil'),
    path('perfil/editar/pass', views.CambiarPass.as_view(), name = 'cambiar_pass'),
    path('resenias', views.listar_resenias, name = 'resenias'),
    path('resenias/postear', views.Postear.as_view(), name = 'postear'),
    path('resenias/editar_resenia/<int:pk>/', views.EditarResenia.as_view(), name='editar_resenia'),
    path('resenias/eliminar_resenia/<int:pk>/', views.EliminarResenia.as_view(), name = 'eliminar_resenia'),
    path('resenias/mostrar/<int:pk>/', views.MostrarResenia.as_view(), name = 'mostrar_resenia'),

]

templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        

        
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type="text/css" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href= {% static 'css/styles.css' %} rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-light bg-light static-top">
            <div class="container">
                <a class="navbar-brand" href={% url 'inicio:inicio' %}>Inicio</a>
                <a class="navbar-brand" href={% url 'inicio:listar_invitados' %}>Lista de Invitados</a>
                <a class="navbar-brand" href={% url 'inicio:listar_djs' %}>Djs</a>
                <a class="navbar-brand" href={% url 'usuario:resenias' %}>Reseñas</a>
                {% if request.user.is_authenticated %} 
                {% if request.user.infousuario.avatar %}
                <img src={{request.user.infousuario.avatar.url}} alt = '' height = '45px' > </img>
                {% endif %}
                <a class="navbar-brand" href={% url 'usuario:perfil' %}>{{request.user.username}}</a>
                <a class="btn btn-secondary" href={% url 'usuario:logout' %}>Cerrar Sesión</a>
                {% else %}
                <a class="btn btn-primary" href={% url 'usuario:login' %}>Iniciar Sesión</a>
                <a class="btn btn-primary" href={% url 'usuario:registro' %}>Registro</a>
                {% endif %}
            </div>
        </nav> 
        {% block header %}
        <header class="masthead">
            <div class="container position-relative">
                <div class="row justify-content-center">
                    <div class="col-xl-6">
                        <div class="text-center text-white">
                            <h1 class="mb-5">
                                {% block mensaje_inicio %}
                                Proyecto 1 - Mauro Silva
                                {% endblock mensaje_inicio %}
                            </h1>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        {% endblock header %}
        {% block contenido %}
        <p>Inicio</p>
        {% endblock contenido %}

        <!-- Footer-->
        <footer class="footer bg-light">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 h-100 text-center text-lg-start my-auto">
                        <ul class="list-inline mb-2">
                            <li class="list-inline-item"><a href={% url 'inicio:about' %}>About</a></li>
                        </ul>
                        <p class="text-muted small mb-4 mb-lg-0">&copy; Mauro Silva 2023. All Rights Reserved.</p>
                    </div>
                    
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>